apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - demo-python-agent-configmap.yaml
  - demo-python-agent-deployment.yaml
  - demo-python-agent-service.yaml

