apiVersion: v1
kind: Service
metadata:
  name: playground-demo-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: demo-agent
  ports:
    - name: http
      port: 8001
      targetPort: http

