apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - demo-agent-deployment.yaml
  - demo-agent-service.yaml

patches:
  - path: patch-control-plane-postgres.yaml
