apiVersion: v1
kind: Service
metadata:
  name: playground-control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 8180
      targetPort: grpc

