apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - control-plane-pvc.yaml
  - control-plane-deployment.yaml
  - control-plane-service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: playground
    includeSelectors: true
