{{- if .Values.controlPlane.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "playground.controlPlane.fullname" . }}
  labels:
    {{- include "playground.labels" . | nindent 4 }}
  {{- with .Values.controlPlane.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.controlPlane.ingress.className }}
  ingressClassName: {{ .Values.controlPlane.ingress.className | quote }}
  {{- end }}
  {{- if .Values.controlPlane.ingress.tls }}
  tls:
    {{- toYaml .Values.controlPlane.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.controlPlane.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "playground.controlPlane.fullname" $ }}
                port:
                  number: {{ $.Values.controlPlane.service.port }}
          {{- end }}
    {{- end }}
{{- end }}

