{{- if .Values.demoPythonAgent.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "playground.fullname" . }}-demo-python-agent
  labels:
    {{- include "playground.labels" . | nindent 4 }}
spec:
  type: {{ .Values.demoPythonAgent.service.type }}
  selector:
    {{- include "playground.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: demo-python-agent
  ports:
    - name: http
      port: {{ .Values.demoPythonAgent.service.port }}
      targetPort: http
{{- end }}

