{{- if .Values.demoBot.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "playground.demoBot.fullname" . }}
  labels:
    {{- include "playground.labels" . | nindent 4 }}
spec:
  type: {{ .Values.demoBot.service.type }}
  selector:
    {{- include "playground.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: demo-bot
  ports:
    - name: http
      port: {{ .Values.demoBot.service.port }}
      targetPort: http
{{- end }}

